import { useState } from "react";

export default function AISuggestPanel({ tasksById, onAccept, onClose, initialResult }) {
  const [result] = useState(initialResult);
  const [busyKey, setBusyKey] = useState(null);
  const [dismissed, setDismissed] = useState(new Set());
  const [expandedKey, setExpandedKey] = useState(null);

  const visible = result.suggestions.filter(
    (s) => !dismissed.has(`${s.predecessorId}->${s.successorId}`)
  );

  const isLlm = result.source === "llm";

  async function handleAccept(s) {
    const key = `${s.predecessorId}->${s.successorId}`;
    setBusyKey(key);
    try {
      await onAccept(s.predecessorId, s.successorId);
      setDismissed((prev) => new Set(prev).add(key));
    } catch {
      // leave visible; addDependency already surfaces its own top-level error
    } finally {
      setBusyKey(null);
    }
  }

  function handleReject(s) {
    setDismissed((prev) => new Set(prev).add(`${s.predecessorId}->${s.successorId}`));
  }

  function toggleExpand(key) {
    setExpandedKey((prev) => (prev === key ? null : key));
  }

  return (
    <div className="tf-modal-overlay fixed inset-0 z-50 flex items-center justify-center p-4">
      <div className="tf-modal w-full max-w-xl shadow-xl">
        <div className="tf-modal-header flex items-center justify-between px-5 py-3.5">
          <div>
            <div className="flex items-center gap-2">
              <h3 className="text-base font-semibold">AI Dependency Suggestions</h3>
              <span
                className={`tf-badge px-2 py-0.5 text-[10px] font-semibold uppercase tracking-wide ${
                  isLlm ? "tf-badge-ready" : "tf-badge-blocked"
                }`}
              >
                {isLlm ? "source: llm" : "source: fallback"}
              </span>
            </div>
            <p className="tf-card-subtext text-[11px] mt-0.5">
              {isLlm
                ? "Generated by the LLM from task titles/descriptions."
                : "AI unavailable \u2014 showing keyword-based fallback suggestions."}
              {" "}Nothing is added until you accept it.
            </p>
          </div>
          <button onClick={onClose} className="tf-card-subtext hover:opacity-70">
            &#10005;
          </button>
        </div>

        <div className="max-h-[60vh] overflow-y-auto px-5 py-4 space-y-3">
          {result.error && result.source !== "llm" && (
            <div className="tf-banner-info rounded-md border px-3 py-2 text-xs" style={{ borderColor: "var(--tf-surface-border)" }}>
              LLM call did not run ({result.error}). Showing a conservative fallback instead &mdash;
              set <code className="font-mono">LLM_API_KEY</code> on the server for real AI suggestions.
            </div>
          )}

          {visible.length === 0 && (
            <p className="tf-card-subtext text-sm text-center py-6">
              No suggestions right now &mdash; either the graph already looks complete, or every
              candidate would have created a cycle.
            </p>
          )}

          {visible.map((s) => {
            const key = `${s.predecessorId}->${s.successorId}`;
            const pred = tasksById[s.predecessorId]?.title || s.predecessorId;
            const succ = tasksById[s.successorId]?.title || s.successorId;
            const isExpanded = expandedKey === key;
            return (
              <div key={key} className="tf-column rounded-lg p-3">
                <div className="flex items-center gap-2 text-sm">
                  <span className="font-medium">{pred}</span>
                  <span className="tf-card-subtext">&rarr;</span>
                  <span className="font-medium">{succ}</span>
                  {typeof s.confidence === "number" && (
                    <span className="tf-card-subtext ml-auto text-[11px]">
                      {Math.round(s.confidence * 100)}% confidence
                    </span>
                  )}
                </div>
                {s.rationale && (
                  <p className="tf-card-subtext mt-1 text-xs">{s.rationale}</p>
                )}

                <button
                  type="button"
                  onClick={() => toggleExpand(key)}
                  className="mt-2 text-[11px] font-medium underline"
                  style={{ color: "var(--tf-accent)" }}
                >
                  {isExpanded ? "Hide details" : "Explain this suggestion"}
                </button>

                {isExpanded && (
                  <div className="tf-pill mt-2 rounded-md p-2 text-[11px] leading-relaxed">
                    <p>
                      <strong>Grounding: </strong>
                      the model was only allowed to choose a predecessor ID from the
                      exact list of existing tasks it was given &mdash; it cannot invent a
                      task that doesn&rsquo;t exist. This suggestion was validated
                      server-side against the real task list before being shown here.
                    </p>
                    <p className="mt-1">
                      <strong>Cycle-safety: </strong>
                      if you accept this, it still passes through the same DAG
                      cycle-detection as a manually created dependency &mdash; the AI
                      never bypasses the core engine&rsquo;s rules.
                    </p>
                  </div>
                )}

                <div className="mt-2 flex justify-end gap-2">
                  <button
                    onClick={() => handleReject(s)}
                    className="tf-btn-secondary rounded-md px-3 py-1 text-xs"
                  >
                    Reject
                  </button>
                  <button
                    onClick={() => handleAccept(s)}
                    disabled={busyKey === key}
                    className="tf-btn-primary rounded-md px-3 py-1 text-xs font-medium"
                  >
                    {busyKey === key ? "Adding\u2026" : "Accept"}
                  </button>
                </div>
              </div>
            );
          })}
        </div>
      </div>
    </div>
  );
}
